apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/justforsachin/demorepo.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: jaeger

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
