apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-application
spec:
  selector:
    matchLabels:
      app: otel-application
  replicas: 3
  template:
    metadata:
      labels:
        app: otel-application
    spec:
      containers:
      - name: otel-application
        image: jaegertracing/all-in-one:1.43
        ports:
        - containerPort: 16686
