apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarger
spec:
  selector:
    matchLabels:
      app: jarger
  replicas: 4
  template:
    metadata:
      labels:
        app: jarger
    spec:
      containers:
      - name: jarger
        image: jaegertracing/all-in-one:1.43
        ports:
        - containerPort: 16686
